site_name: Palbot
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: indigo
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - Setup: setup.md
  - Commands: commands.md
  - Kits: kits.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dkoz
    - icon: fontawesome/brands/discord
      link: https://discord.gg/3HUq8cJSrX