site_name: Palbot
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate
nav:
  - Home: index.md
  - Setup: setup.md
  - Commands: commands.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dkoz
    - icon: fontawesome/brands/discord
      link: https://discord.gg/3HUq8cJSrX